language: objective-c
xcode_project: 003---CI.xcodeproj # path to your xcodeproj folder
xcode_scheme: 003---CI
osx_image: xcode9.4

script:
- set -o pipefail
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "name=iPhone 7" -enableCodeCoverage YES | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
