osx_image: xcode7.3
language: objective-c
xcode_project: 003---CI.xcodeproj
script: xcodebuild -project 003---CI.xcodeproj -scheme "003---CI" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'

